Repository space-401/FrontEnd, pull requests merged in 2023-08, with the labels that each got.

#3 [FE] 테마를 추가하였습니다.
  client/src/styles/themes/colors.ts
  client/src/styles/themes/font_size.ts
  client/src/styles/themes/index.ts
  client/src/styles/themes/palette.ts
  client/src/styles/themes/theme.ts
Labels: ⚛️프론트엔드, 🎨 디자인

#8 [FE] 협업세팅 설정하기
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/main.tsx
  client/src/stories/Button.stories.ts
  client/src/stories/Button.tsx
  client/src/stories/Configure.mdx
  client/src/stories/Header.tsx
  client/src/stories/Page.tsx
  client/src/styles/themes/colors.ts
  client/src/styles/themes/font_size.ts
  client/src/styles/themes/index.ts
  client/src/styles/themes/palette.ts
  client/src/styles/themes/theme.ts
  client/src/vite-env.d.ts
  client/yarn.lock
Labels: ⚙️설정, ⚛️프론트엔드, ✏️ 문서

#9 [FE] 스토리북 CI 서비스, 배포 추가
  .github/workflows/chromatic.yml
  client/build-storybook.log
  client/package-lock.json
  client/package.json
Labels: ⚙️설정, ⚛️프론트엔드, 🤖 기능

#16 [FE] styled-component 추가
  .github/workflows/chromatic.yml
  client/package-lock.json
  client/package.json
Labels: ⚙️설정, ⚛️프론트엔드

#17 [FE] 스토리북 배포 테스트를 위한 병합
  .github/workflows/chromatic.yml
  client/package-lock.json
  client/package.json
Labels: ⚙️설정, ⚛️프론트엔드

#21 [FE] Storybook 설정 완료
  .github/workflows/chromatic.yml
  client/.storybook/main.ts
  client/src/stories/Header.stories.ts
  client/src/stories/Header.tsx
  client/src/stories/header.css
  client/tsconfig.node.json
  client/vite.config.ts
Labels: ⚙️설정, ⚛️프론트엔드, 🐛 버그

#22 Feat/post page
  .travis.yml
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/assets/svg/alarmIcon.svg
  client/src/assets/svg/logo.svg
  client/src/assets/svg/personIcon.svg
  client/src/components/StyledButton/StyledButton.stories.tsx
  client/src/components/StyledButton/index.tsx
  client/src/components/layout/Header/Header.tsx
  client/src/components/layout/LoginLayout.tsx
  client/src/components/layout/MainLayout.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/router/.gitkeep
  client/src/router/Router.tsx
  client/src/stories/Button.stories.ts
  client/src/stories/Header.stories.ts
  client/src/stories/Page.stories.ts
  client/src/stories/Page.tsx
  client/src/stories/StyledButton.stories.tsx
  client/src/styles/.gitkeep
  client/src/styles/common.ts
  client/src/styles/global.ts
  client/src/styles/reset.ts
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#23 🚀chore : react-router-dom type 추가
  client/package-lock.json
  client/package.json
  client/src/router/Router.tsx
Labels: ⚙️설정, 🏭 개발

#24 [FE] 코드 포멧팅 적용
  client/package-lock.json
  client/src/App.tsx
  client/src/components/StyledButton/index.tsx
  client/src/main.tsx
  client/src/stories/Header.tsx
  client/src/stories/index.tsx
  client/src/styles/common.ts
  client/src/styles/reset.ts
Labels: ⚙️설정, ⚛️프론트엔드, 🎨 마크업 & 스타일링

#25 [FE] 게시물 페이지 작업 진행, 라이브러리 추가
  .github/workflows/chromatic.yml
  client/.eslintrc.cjs
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/.storybook/preview.tsx
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/.gitkeep
  client/src/components/common/FlipCard/FlipCard.stories.tsx
  client/src/components/common/FlipCard/index.tsx
  client/src/components/common/FlipCard/style.ts
  client/src/components/common/SelectBox/SelectBox.stories.tsx
  client/src/components/common/SelectBox/index.tsx
  client/src/router/KkliriProvider.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#27 [FE] BasicBox, Header UI를 추가하였습니다
  client/index.html
  client/src/App.tsx
  client/src/assets/svg/KKIRI.svg
  client/src/assets/svg/alarmIcon.svg
  client/src/assets/svg/logo.svg
  client/src/assets/svg/react.svg
  client/src/assets/svg/vite.svg
  client/src/components/StyledButton/StyledButton.stories.tsx
  client/src/components/StyledButton/index.tsx
  client/src/components/common/BasicBox/BasicBox.stories.tsx
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/layout/Header/Header.stories.tsx
  client/src/components/layout/Header/Header.tsx
  client/src/components/layout/Header/style.ts
  client/src/components/layout/MainLayout.tsx
  client/src/custom.d.ts
  client/src/stories/Page.stories.ts
  client/src/styles/global.ts
  client/src/utils/KkiriProvider.tsx
Labels: ⚛️프론트엔드, 🎨 디자인

#29 [FE] 인풋 컴포넌트 퍼블리싱
  client/src/App.tsx
  client/src/assets/cat.jpg
  client/src/assets/svg/deleteIcon.svg
  client/src/assets/svg/photoIcon.svg
  client/src/assets/svg/questionIcon.svg
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/CircleIcon/CircleIcon.tsx
  client/src/components/common/InputBox/InputBox.tsx
  client/src/components/common/TextAreaBox/TextAreaBox.tsx
  client/src/components/layout/FullScreenModal.tsx
  client/src/components/layout/Header/Header.tsx
  client/src/components/layout/Header/style.ts
  client/src/components/layout/HeaderLayout.tsx
  client/src/components/layout/LoginLayout.tsx
  client/src/components/layout/MainLayout.tsx
  client/src/pages/.gitkeep
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/InviteCode.tsx
  client/src/pages/InviteCode/style.ts
  client/src/router/Router.tsx
  client/src/stories/Page.stories.ts
  client/src/stories/Page.tsx
  client/src/stories/StyledButton.stories.tsx
  client/src/stories/index.tsx
  client/src/stories/page.css
  client/src/styles/global.ts
  client/src/styles/reset.ts
  client/src/styles/themes/font_size.ts
  client/src/styles/themes/palette.ts
  client/src/utils/CombinedProvider.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링
