Repository space-401/FrontEnd, pull requests merged in 2023-10, with the labels that each got.

#95 [FE] 소셜 로그인 진행 중
  client/.env.sample
  client/package-lock.json
  client/package.json
  client/src/components/Auth/SocialGoogle.tsx
  client/src/components/Auth/SocialKakao.tsx
  client/src/components/Auth/SocialNaver.tsx
  client/src/components/Create/ImageEditModal/ImageEditModal.tsx
  client/src/components/Create/ImageEditModal/ImagesEditModal.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/InputBox/style.ts
  client/src/constants/api.ts
  client/src/constants/path.ts
  client/src/pages/Auth/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/InviteCode/index.tsx
  client/src/pages/Landing/index.tsx
  client/src/pages/Landing/style.ts
  client/src/pages/SelectSpace/index.tsx
  client/src/pages/SelectSpace/style.ts
  client/src/router/Router.tsx
  client/src/utils/KkiriProvider.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#97 [BE] Spring Boot kkiri 프로젝트 생성
  .gitignore
  server/.gitignore
  server/.gitkeep
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/app/kkiri/KkiriApplication.java
  server/src/main/java/com/app/kkiri/mapper/TimeMapper.java
  server/src/main/java/com/app/kkiri/myBatis/MyBatisConfig.java
  server/src/main/resources/application.properties
  server/src/main/resources/config/config.xml
  server/src/main/resources/mapper/TimMapper.xml
  server/src/main/resources/static/index.html
  server/src/test/java/com/app/kkiri/KkiriApplicationTests.java
  server/src/test/java/com/app/kkiri/mapper/TimeMapperTest.java
Labels: ⚙️설정, 🖥️백엔드

#98 [FE] 포스트 생성시 지도 좌표 선택버튼 추가
  client/src/components/Create/SearchMapModal/index.tsx
  client/src/components/Create/SearchMapModal/style.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#99 [FE] 마이페이지 댓글 퍼블리싱 수정완료
  client/src/assets/svg/feather.svg
  client/src/constants/api.ts
  client/src/constants/path.ts
  client/src/mocks/data/MyPage/commentListMock.ts
  client/src/pages/MyPage/MyBody/components/BookMarkList.tsx
  client/src/pages/MyPage/MyBody/components/MyCommentList.tsx
  client/src/pages/MyPage/MyBody/components/style.ts
  client/src/pages/MyPage/MyBody/index.tsx
  client/src/pages/MyPage/MyBody/style.ts
  client/src/pages/MyPage/Navbar/index.tsx
  client/src/pages/MyPage/Navbar/style.ts
  client/src/pages/MyPage/components/AccountManagement.tsx
  client/src/pages/MyPage/components/BookMarkList.tsx
  client/src/pages/MyPage/components/MyCommentList.tsx
  client/src/pages/MyPage/components/MyPostList.tsx
  client/src/pages/MyPage/components/MyPostOrCommentList.tsx
  client/src/pages/MyPage/components/style.ts
  client/src/pages/MyPage/index.tsx
  client/src/pages/MyPage/style.ts
  client/src/router/Router.tsx
  client/src/types/space.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#103 [FE] 일부 충돌 코드 수정
  client/src/apis/post/getPostDetail.ts
  client/src/components/Create/CreateSelectBox/SelectBox.stories.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/Calender/MainCalender.tsx
  client/src/hooks/api/post/usePostDetailQuery.ts
  client/src/layout/HeaderLayout/Header.tsx
  client/src/mocks/data/MyPage/MyPageMock.ts
  client/src/mocks/data/post.mock.ts
  client/src/mocks/data/user.mock.ts
  client/src/mocks/handlers/user.ts
  client/src/modal/Detail/index.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/Main/PostList/PostList.tsx
  client/src/types/post.type.ts
  client/src/types/space.type.ts
Labels: ⚛️프론트엔드, 🏭 개발

#104 [FE] 모달, 레이아웃 추가
  client/.env.sample
  client/src/apis/post/getPostDetail.ts
  client/src/components/Create/CreateSelectBox/index.tsx
  client/src/components/Create/SearchMapModal/component/MapBox.tsx
  client/src/components/Main/Comments/index.tsx
  client/src/components/Main/PostMap/components/LeftSection.tsx
  client/src/components/Main/PostMap/index.tsx
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/UserList.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/hooks/common/useAlertMessage.ts
  client/src/hooks/common/useAlertModalOpen.ts
  client/src/hooks/common/useConfirmModalOpen.ts
  client/src/hooks/common/useDetailModalOpen.ts
  client/src/layout/HeaderLayout/HeaderLayout.tsx
  client/src/layout/HeaderLayout/style.ts
  client/src/mocks/data/post.mock.ts
  client/src/modal/Alert/AlertModal.tsx
  client/src/modal/Alert/index.tsx
  client/src/modal/Confirm/index.tsx
  client/src/modal/Detail/index.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/InviteCode/InviteCode.stories.tsx
  client/src/pages/InviteCode/index.tsx
  client/src/pages/Main/PostList/PostList.tsx
  client/src/pages/MyPage/components/BookMarkList.tsx
  client/src/pages/MyPage/components/MyCommentList.tsx
  client/src/pages/MyPage/components/MyPostList.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/SelectSpace/style.ts
  client/src/store/modal.ts
  client/src/types/modal.type.ts
Labels: ⚙️설정, ⚛️프론트엔드

#105 [FE] 라우터 추가, 사이드 모달 코드 수정
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/UserList.tsx
  client/src/constants/path.ts
  client/src/mocks/data/Header/header.mock.ts
  client/src/mocks/data/MyPage/MyPageMock.ts
  client/src/mocks/data/space.mock.ts
  client/src/pages/Main/MainHeader/MainHeader.tsx
  client/src/router/Router.tsx
  client/src/stories/.gitkeep
Labels: ⚛️프론트엔드

#106 [FE] 생성 레이아웃 반응형 수정
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/InputBox/style.ts
  client/src/constants/path.ts
  client/src/layout/BackLayout/index.tsx
  client/src/layout/BackLayout/style.ts
  client/src/mocks/data/post.mock.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/Main/MainHeader/MainHeader.tsx
  client/src/router/Router.tsx
  client/src/types/post.type.ts
  client/src/utils/fileConvertor.ts
Labels: ⚛️프론트엔드, 🏭 개발

#107 📝fix : 타입 에러 수정
  client/src/components/Main/PostMap/components/LeftSection.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/FlipCard/Back/PostInfoBack.tsx
  client/src/components/common/FlipCard/Back/style.ts
  client/src/components/common/FlipCard/style.ts
  client/src/mocks/data/post.mock.ts
  client/src/modal/Detail/index.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/SelectSpace/style.ts
  client/src/types/post.type.ts
  client/src/types/space.type.ts
  client/src/utils/formatter.ts
Labels: ⚛️프론트엔드, 🏭 개발

#108 [FE] 라우터 수정
  client/src/constants/path.ts
  client/src/layout/HeaderLayout/Header.tsx
  client/src/mocks/data/post.mock.ts
  client/src/pages/Main/PostList/PostList.tsx
  client/src/router/Router.tsx
  client/src/types/post.type.ts
Labels: ⚛️프론트엔드, 🔨 수정

#109 [FE] 메인 페이지 라우터 경로 수정
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/UserList.tsx
  client/src/components/Main/Setting/components/style.ts
  client/src/modal/Detail/index.tsx
  client/src/pages/Main/MainHeader/MainHeader.tsx
  client/src/pages/Main/index.tsx
  client/src/types/main.type.ts
  client/src/utils/toastMessage.ts
Labels: ⚛️프론트엔드, 🔨 수정

#110 [FE] 메인 페이지 퍼블리싱 수정
  client/src/components/Main/PostMap/components/style.ts
  client/src/components/Main/PostMap/style.ts
  client/src/components/common/FlipCard/Back/PostInfoBack.tsx
  client/src/components/common/FlipCard/Back/style.ts
  client/src/components/common/FlipCard/style.ts
  client/src/components/common/Pagination/index.tsx
  client/src/components/common/Pagination/style.ts
  client/src/pages/Main/MainHeader/style.ts
  client/src/pages/Main/PostList/PostList.tsx
  client/src/pages/Main/PostList/style.ts
  client/src/styles/reset.ts
Labels: ⚛️프론트엔드, 🔨 수정, 🎨 디자인

#111 [FE] 스페이스 수정 기능 추가
  client/src/apis/post/getPostDetail.ts
  client/src/apis/post/patchPost.ts
  client/src/apis/post/postPost.ts
  client/src/apis/space/getSpaceDetail.ts
  client/src/apis/space/getSpacePostList.ts
  client/src/assets/mock/imgString
  client/src/components/Main/SearchBox/index.tsx
  client/src/constants/path.ts
  client/src/hooks/api/post/usePostDeleteMutation.ts
  client/src/hooks/api/post/usePostDetailQuery.ts
  client/src/hooks/api/post/usePostMutation.ts
  client/src/hooks/api/space/useSpaceInfoQuery.ts
  client/src/mocks/data/space.mock.ts
  client/src/modal/Detail/index.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/Main/PostList/PostList.tsx
  client/src/router/Router.tsx
  client/src/types/main.type.ts
  client/src/types/post.type.ts
  client/src/types/space.type.ts
  client/src/utils/selectTypeConvertor.ts
Labels: ⚛️프론트엔드, 🏭 개발

#112 [FE] main 페이지 임시수정
  client/src/components/Main/PostMap/index.tsx
  client/src/components/common/FlipCard/style.ts
  client/src/layout/BackLayout/index.tsx
  client/src/layout/HeaderLayout/Header.tsx
  client/src/layout/HeaderLayout/style.ts
  client/src/pages/Main/MainHeader/style.ts
  client/src/pages/Main/PostList/style.ts
  client/src/pages/Main/style.ts
  client/src/pages/MyPage/style.ts
  client/src/pages/SelectSpace/index.tsx
  client/src/pages/SelectSpace/style.ts
Labels: ⚛️프론트엔드, 🎨 디자인

#113 [FE] 초기 유저정보 설정 모달 진행중
  client/.storybook/main.ts
  client/.storybook/preview.tsx
  client/package.json
  client/src/apis/space/patchSpace.ts
  client/src/apis/space/postSpace.ts
  client/src/apis/space/postSpaceTag.ts
  client/src/assets/svg/goArrowIcon.svg
  client/src/assets/svg/profileMock.svg
  client/src/components/Auth/SocialKakao.tsx
  client/src/components/Auth/SocialNaver.tsx
  client/src/components/Create/BasicIconModal/index.tsx
  client/src/components/Create/CreateSelectBox/index.tsx
  client/src/components/Create/CreateUserModal/index.tsx
  client/src/components/Create/ImageEditModal/CircleCropper.module.css
  client/src/components/Create/ImageEditModal/CircleCropper.tsx
  client/src/components/Create/ImageEditModal/Cropper.css
  client/src/components/Create/ImageEditModal/Cropper.tsx
  client/src/components/Create/ImageEditModal/ImageEditModal.tsx
  client/src/components/Create/ImageEditModal/ImagesEditModal.tsx
  client/src/components/Create/ImageEditModal/style.ts
  client/src/components/Create/ImgSlider/index.tsx
  client/src/components/Create/MultipleImgBox/style.ts
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/ProfileAndUserNameChangeModal.tsx
  client/src/components/Main/WelcomeAndSettingModal/FirstSettingModal.tsx
  client/src/components/Main/WelcomeAndSettingModal/WelcomeModal.tsx
  client/src/components/Main/WelcomeAndSettingModal/index.tsx
  client/src/components/Main/WelcomeAndSettingModal/style.ts
  client/src/components/common/BasicButton/BasicButton.stories.tsx
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/CircleIcon/CircleIcon.stories.tsx
  client/src/components/common/InputBox/InputBox.stories.tsx
  client/src/components/common/InputBox/index.tsx
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/TextAreaBox.stories.tsx
  client/src/components/common/UserSettingModal/UserList.tsx
  client/src/components/common/UserSettingModal/index.tsx
  client/src/components/common/UserSettingModal/style.ts
  client/src/constants/api.ts
  client/src/constants/auth.ts
  client/src/layout/BackLayout/index.tsx
  client/src/layout/BackLayout/style.ts
  client/src/mocks/data/space.mock.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/SelectSpace/style.ts
  client/src/store/modal.ts
  client/src/store/user.ts
  client/src/types/main.type.ts
  client/src/types/space.type.ts
  client/tsconfig.json
Labels: ⚛️프론트엔드, 🏭 개발

#116 🚀chore : 버그 임시수정 확인필요
  src/components/Create/CreateSelectBox/SelectBox.stories.tsx
  src/components/Main/Setting/style.ts
  src/components/common/Calender/Calender.tsx
  src/pages/Main/MainHeader/MainHeader.tsx
Labels: ❗우선순위 : 상, ⚛️프론트엔드

#119 🌈feat : 메인페이지 포스트 리스트 제외 수정완료
  src/assets/mock/space6.svg
  src/assets/png/DefaultImg.png
  src/assets/svg/KKIRI.svg
  src/components/Main/SearchBox/index.tsx
  src/components/Main/SearchBox/style.ts
  src/components/Main/SelectBox/components/Toggle.tsx
  src/components/Main/SelectBox/index.tsx
  src/components/Main/SelectBox/style.ts
  src/components/common/AvatarGroup/style.ts
  src/components/common/Calender/Calender.tsx
  src/components/common/FlipCard/style.ts
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/style.ts
  src/mocks/data/comment.mock.ts
  src/mocks/data/common.ts
  src/mocks/data/post.mock.ts
  src/mocks/data/space.mock.ts
  src/pages/Main/MainHeader/MainHeader.tsx
  src/pages/Main/MainHeader/style.ts
  src/pages/Main/PostList/PostList.tsx
  src/pages/Main/PostList/style.ts
  src/types/main.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#120 🌈feat: 메인페이지, 마이페이지 레이아웃 변경 완료
  package-lock.json
  public/_redirects
  src/assets/svg/folder.svg
  src/components/common/AvatarGroup/Avatars.tsx
  src/components/common/AvatarGroup/style.ts
  src/components/common/FlipCard/Back/style.ts
  src/components/common/Pagination/style.ts
  src/constants/api.ts
  src/layout/HeaderLayout/style.ts
  src/mocks/data/post.mock.ts
  src/mocks/data/user.mock.ts
  src/modal/Detail/index.tsx
  src/modal/Detail/style.ts
  src/pages/MyPage/components/BookMarkList.tsx
  src/pages/MyPage/components/MyCommentList.tsx
  src/pages/MyPage/components/MyPostList.tsx
  src/pages/MyPage/components/MyPostOrCommentList.tsx
  src/pages/MyPage/components/OneMyPostList.tsx
  src/pages/MyPage/components/style.ts
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/router/Router.tsx
  src/types/post.type.ts
  src/types/user.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#122 [FE] 유저 프로필 변경 모달을 변경 디자인으로 수정
  src/assets/svg/mainCalender.svg
  src/components/Create/ImageEditModal/CircleCropper.module.css
  src/components/Create/ImageEditModal/CircleCropper.tsx
  src/components/Create/ImageEditModal/Cropper.tsx
  src/components/Create/ImageEditModal/ImageEditModal.tsx
  src/components/Create/ImageEditModal/ImagesEditModal.tsx
  src/components/Create/ImageEditModal/style.ts
  src/components/Create/ImgSlider/index.tsx
  src/components/Create/MultipleImgBox/style.ts
  src/components/Create/SelectIconModal/index.tsx
  src/components/Create/SelectIconModal/style.ts
  src/components/Main/WelcomeAndSettingModal/FirstSettingModal.tsx
  src/components/Main/WelcomeAndSettingModal/SettingModal.tsx
  src/components/Main/WelcomeAndSettingModal/index.tsx
  src/components/common/Calender/Calender.tsx
  src/components/common/FlipCard/Back/PostInfoBack.tsx
  src/components/common/UserSettingModal/UserList.tsx
  src/pages/Main/PostList/PostList.tsx
  src/pages/Main/index.tsx
  src/store/modal.ts
Labels: ⚛️프론트엔드, 🏭 개발

#123 🌈feat : skeletonPage를 추가하였습니다.
  .gitignore
  src/components/Create/ImageEditModal/ImageEditModal.tsx
  src/components/Create/ImageEditModal/ImagesEditModal.tsx
  src/components/Create/ImageEditModal/style.ts
  src/components/Create/ImgSlider/index.tsx
  src/components/Create/SelectIconModal/style.ts
  src/components/Main/PostMap/PostMap.Skeleton.tsx
  src/components/Main/PostMap/components/LeftSection.Skeleton.tsx
  src/components/Main/PostMap/components/One-PostMapCard.Skeleton.tsx
  src/components/Main/PostMap/components/style.ts
  src/components/common/FlipCard/Back/PostInfoBack.tsx
  src/components/common/Skeleton/index.tsx
  src/components/common/UserSettingModal/UserList.tsx
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/Skeleton/index.tsx
  src/layout/HeaderLayout/index.tsx
  src/modal/Detail/Skeleton/index.tsx
  src/modal/Detail/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/Main/MainBody/MainBody.tsx
  src/pages/Main/MainBody/MainBodySkeleton.tsx
  src/pages/Main/MainBody/style.ts
  src/pages/Main/MainHeader/MainHeader.skeleton.tsx
  src/pages/Main/MainHeader/MainHeader.tsx
  src/pages/Main/Skeleton/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/Skeleton/AccountManagement.skeleton.tsx
  src/pages/MyPage/Skeleton/BookMarkList.skeleton.tsx
  src/pages/MyPage/Skeleton/MyCommentList.skeleton.tsx
  src/pages/MyPage/Skeleton/MyPostList.skeleton.tsx
  src/pages/MyPage/Skeleton/OneTableList.skeleton.tsx
  src/pages/MyPage/Skeleton/index.tsx
  src/pages/MyPage/components/BookMarkList.tsx
  src/pages/MyPage/components/MyPostList.tsx
  src/pages/MyPage/components/MyPostOrCommentList.tsx
  src/pages/MyPage/components/style.ts
  src/pages/MyPage/index.tsx
  src/router/Router.tsx
  src/styles/global.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#124 📝fix: 레이아웃 변경에 따른 코드 변경
  src/assets/mock/space6.svg
  src/assets/svg/KKIRI.svg
  src/assets/svg/defaultImg/img1.svg
  src/assets/svg/defaultImg/img2.svg
  src/assets/svg/defaultImg/img3.svg
  src/assets/svg/defaultImg/img4.svg
  src/assets/svg/defaultImg/img5.svg
  src/assets/svg/headerLogo.svg
  src/assets/svg/selectlogo.svg
  src/assets/svg/signlogo.svg
  src/components/Main/MainBody/MainBody.tsx
  src/components/Main/MainBody/MainBodySkeleton.tsx
  src/components/Main/MainBody/style.ts
  src/components/Main/MainHeader/MainHeader.skeleton.tsx
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/MainHeader/style.ts
  src/components/Main/Skeleton/index.tsx
  src/components/MyPage/AccountManagement.tsx
  src/components/MyPage/BookMarkList.tsx
  src/components/MyPage/MyCommentList.tsx
  src/components/MyPage/MyPostList.tsx
  src/components/MyPage/MyPostOrCommentList.tsx
  src/components/MyPage/OneMyPostList.tsx
  src/components/MyPage/Skeleton/AccountManagement.skeleton.tsx
  src/components/MyPage/Skeleton/BookMarkList.skeleton.tsx
  src/components/MyPage/Skeleton/MyCommentList.skeleton.tsx
  src/components/MyPage/Skeleton/MyPostList.skeleton.tsx
  src/components/MyPage/Skeleton/OneTableList.skeleton.tsx
  src/components/MyPage/Skeleton/index.tsx
  src/components/MyPage/style.ts
  src/components/common/FlipCard/Back/PostInfoBack.tsx
  src/components/common/FlipCard/Back/SpaceInfoBack.tsx
  src/components/common/FlipCard/Back/style.ts
  src/components/common/FlipCard/FlipCard.tsx
  src/components/common/FlipCard/style.ts
  src/components/common/Pagination/style.ts
  src/constants/policy.ts
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/Skeleton/index.tsx
  src/layout/HeaderLayout/style.ts
  src/pages/Landing/index.tsx
  src/pages/Main/MainBody/MainBodySkeleton.tsx
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
  src/pages/MyPage/index.tsx
  src/pages/SelectSpace/index.tsx
  src/pages/SelectSpace/style.ts
  src/pages/Sign/index.tsx
  src/pages/Sign/style.ts
  src/router/Router.tsx
  src/router/lazy.ts
  src/styles/reset.ts
  src/types/post.type.ts
Labels: ⚛️프론트엔드, 🔨 수정, 🎨 디자인

#126 🌈feat : 유저 정보 수정 새로운 디자인으로 변경, 닉네임 중복 검사
  src/components/Create/ImgSlider/index.tsx
  src/components/Main/Setting/SettingComponent.tsx
  src/components/Main/WelcomeAndSettingModal/FirstSettingModal.tsx
  src/components/Main/WelcomeAndSettingModal/SettingModal.tsx
  src/components/Main/WelcomeAndSettingModal/UserSettingModal.tsx
  src/components/Main/WelcomeAndSettingModal/WelcomeModal.tsx
  src/components/Main/WelcomeAndSettingModal/index.tsx
  src/components/common/UserSettingModal/UserList.tsx
  src/components/common/UserSettingModal/index.tsx
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/Main/index.tsx
  src/store/modal.ts
Labels: ⚛️프론트엔드, 🏭 개발

#127 🌈feat : 북마크 기능, 허스키 추가
  .env.sample
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
  src/App.tsx
  src/components/Detail/Skeleton/index.tsx
  src/components/Main/MainBody/MainBody.tsx
  src/components/Main/MainBody/MainBodySkeleton.tsx
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/Setting/SettingComponent.tsx
  src/hooks/api/post/useBookMarkMutation.ts
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/Skeleton/Layout/index.tsx
  src/layout/HeaderLayout/index.tsx
  src/modal/Detail/index.tsx
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/InviteCode/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/style.ts
  src/pages/SelectSpace/index.tsx
  src/utils/formatter.ts
Labels: ⚙️설정, ⚛️프론트엔드, 🎨 디자인

#128 🌈feat : 필터 모달 작업 중
  src/apis/space/deleteSpaceTag.ts
  src/apis/space/getSpaceTag.ts
  src/assets/basicSpaceImg/SpaceOne.jpg
  src/assets/basicSpaceImg/spaceFive.jpg
  src/assets/basicSpaceImg/spaceFour.jpg
  src/assets/basicSpaceImg/spaceThree.jpg
  src/assets/basicSpaceImg/spaceTwo.jpg
  src/assets/png/DefaultImg.png
  src/assets/svg/deleteIcon.svg
  src/assets/svg/photo/smallDeleteIcon.svg
  src/assets/svg/smallDeleteIcon.svg
  src/assets/svg/tagEditIcon.svg
  src/components/Create/BasicIconModal/BasicIcon.tsx
  src/components/Create/CharacterCounter/style.ts
  src/components/Create/ImageEditModal/Cropper.tsx
  src/components/Create/ImgSlider/index.tsx
  src/components/Create/MultipleImgBox/index.tsx
  src/components/Create/MultipleImgBox/style.ts
  src/components/Create/TagEditModal/TagList.tsx
  src/components/Create/TagEditModal/index.tsx
  src/components/Create/TagEditModal/style.ts
  src/components/Main/MainBody/MainBody.tsx
  src/components/Main/MainBody/MainBodySkeleton.tsx
  src/components/Main/MainHeader/style.ts
  src/components/Main/SearchBox/style.ts
  src/components/Main/SelectBox/style.ts
  src/components/Main/Setting/SettingComponent.tsx
  src/components/Main/WelcomeAndSettingModal/UserSettingModal.tsx
  src/components/common/Calender/Calender.tsx
  src/components/common/InputBox/index.tsx
  src/components/common/InputBox/style.ts
  src/components/common/TextAreaBox/style.ts
  src/hooks/api/space/useSpaceTagQuery.ts
  src/layout/HeaderLayout/style.ts
  src/mocks/data/space.mock.ts
  src/mocks/handlers/space.ts
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/CreateSpace/style.ts
  src/store/modal.ts
Labels: ⚛️프론트엔드, 🏭 개발

#129 🚧refactor : 일부 전역 모달 상태 코드 변경
  src/components/Create/BasicIconModal/index.tsx
  src/components/Create/BasicIconModal/style.ts
  src/components/Create/CreateUserModal/index.tsx
  src/components/Create/CreateUserModal/style.ts
  src/components/Create/ImageEditModal/ImageEditModal.tsx
  src/components/Create/ImageEditModal/style.ts
  src/components/Create/SearchMapModal/style.ts
  src/components/Create/SelectIconModal/style.ts
  src/components/Create/TagEditModal/style.ts
  src/components/Main/WelcomeAndSettingModal/style.ts
  src/components/common/UserSettingModal/style.ts
  src/modal/Alert/style.ts
  src/modal/Confirm/style.ts
  src/modal/Detail/style.ts
  src/pages/CreateSpace/index.tsx
  src/store/modal.ts
  src/styles/common.ts
Labels: ⚛️프론트엔드, 🏭 개발

#130 ⚒️fix : 이미지 모달 코드 수정
  src/apis/space/postSpace.ts
  src/components/Create/ImageEditModal/ImageEditModal.tsx
  src/components/Create/ImageEditModal/ImagesEditModal.tsx
  src/components/Create/MultipleImgBox/index.tsx
  src/components/Create/SelectIconModal/index.tsx
  src/components/Create/TagEditModal/index.tsx
  src/components/Main/WelcomeAndSettingModal/UserSettingModal.tsx
  src/components/common/CircleIcon/CircleIcon.tsx
  src/components/common/CircleIcon/style.ts
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/CreateSpace/style.ts
  src/types/image.type.ts
  src/types/space.type.ts
  src/utils/makeObj.ts
Labels: ⚛️프론트엔드, 🏭 개발

#131 🌈feat : 페이지네이션 작업 완료
  src/components/Create/SearchMapModal/component/Pagination.tsx
  src/components/Create/SearchMapModal/index.tsx
  src/components/Create/SearchMapModal/style.ts
  src/components/Main/MainBody/MainBody.tsx
  src/components/Main/PostMap/components/LeftSection.tsx
  src/components/Main/PostMap/components/style.ts
  src/components/Main/PostMap/index.tsx
  src/components/Main/SelectBox/components/component/UserList.tsx
  src/components/Main/SelectBox/style.ts
  src/components/common/Pagination/index.tsx
  src/mocks/data/post.mock.ts
  src/types/main.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#132 📝fix : 빌드 에러 수정
  package-lock.json
  src/pages/CreatePost/index.tsx
  src/pages/InviteCode/index.tsx
  src/pages/InviteCode/style.ts
Labels: ⚛️프론트엔드, 🏭 개발

#133 🌈feat : 랜딩페이지 임시추가
  package-lock.json
  package.json
  public/manifest.json
  src/App.tsx
  src/assets/basicSpaceImg/SpaceOne.jpg
  src/assets/basicSpaceImg/spaceFive.jpg
  src/assets/basicSpaceImg/spaceFour.jpg
  src/assets/basicSpaceImg/spaceThree.jpg
  src/assets/basicSpaceImg/spaceTwo.jpg
  src/assets/png/logo/logo.png
  src/assets/svg/landing/fourth_right.svg
  src/assets/svg/landing/second_right.svg
  src/assets/svg/landing/third_left.svg
  src/components/Create/BasicIconModal/BasicIcon.tsx
  src/components/Landing/FirstSection.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/FourthSection.tsx
  src/components/Landing/SecondSection.tsx
  src/components/Landing/ThirdSection.tsx
  src/components/Landing/style.ts
  src/components/Main/MainHeader/style.ts
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Landing/style.ts
  src/router/Router.tsx
  vite.config.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#134 💄style : 코드 포맷팅누락
  src/components/Create/BasicIconModal/style.ts
  src/components/Create/CharacterCounter/style.ts
  src/components/Create/CreateSelectBox/index.tsx
  src/components/Create/ImageEditModal/style.ts
  src/components/Create/SelectIconModal/style.ts
  src/components/Create/TagEditModal/style.ts
  src/components/Landing/style.ts
  src/components/Main/MainBody/MainBody.tsx
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/SearchBox/index.tsx
  src/components/Main/SearchBox/style.ts
  src/components/Main/SelectBox/index.tsx
  src/components/Main/SelectBox/style.ts
  src/components/Main/Setting/SettingComponent.tsx
  src/components/Main/Setting/style.ts
  src/components/Main/WelcomeAndSettingModal/style.ts
  src/components/common/InputBox/index.tsx
  src/components/common/UserSettingModal/style.ts
  src/constants/path.ts
  src/modal/Alert/style.ts
  src/modal/Confirm/style.ts
  src/modal/Detail/style.ts
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/CreateSpace/style.ts
  src/pages/InviteCode/style.ts
  src/pages/Landing/index.tsx
  src/pages/Landing/style.ts
  src/types/main.type.ts
  src/vite-env.d.ts
Labels: ⚙️설정, ⚛️프론트엔드

#135 🌈feat : 랜딩페이지 완성
  package-lock.json
  package.json
  src/assets/svg/landing/arrow_right.svg
  src/assets/svg/landing/foruth_background.svg
  src/assets/svg/landing/fourth_left.svg
  src/assets/svg/landing/landing_bottom.svg
  src/assets/svg/landing/landing_top.svg
  src/assets/svg/landing/second_left.svg
  src/assets/svg/landing/third_right.svg
  src/components/Landing/FifthSection.tsx
  src/components/Landing/FirstSection.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/FourthSection.tsx
  src/components/Landing/SecondSection.tsx
  src/components/Landing/ThirdSection.tsx
  src/components/Landing/style.ts
  src/components/Main/MainBody/MainBody.tsx
  src/hooks/common/useCss.ts
  src/hooks/common/useScript.ts
  src/pages/Landing/index.tsx
  src/pages/Landing/style.ts
  src/pages/Main/index.tsx
  src/router/Router.tsx
  src/types/main.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#136 🌈feat : 로그인 로그아웃기능 임시구현
  src/App.tsx
  src/apis/HTTPError.ts
  src/apis/interceptors.ts
  src/apis/user/deleteKkiriUser.ts
  src/apis/user/getLogout.ts
  src/apis/user/postLogin.ts
  src/assets/index.d.ts
  src/components/Landing/FirstSection.tsx
  src/components/MyPage/AccountManagement.tsx
  src/components/MyPage/Skeleton/OneTableList.skeleton.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/user/useDeleteKkiriUserMutation.ts
  src/hooks/api/user/useLogInMutation.ts
  src/hooks/api/user/useLogOutMutation.ts
  src/hooks/api/user/useLogOutQuery.ts
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/Skeleton/Header/index.tsx
  src/layout/HeaderLayout/index.tsx
  src/mocks/data/user.mock.ts
  src/mocks/handlers/user.ts
  src/pages/Auth/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Loading/index.tsx
  src/pages/Loading/style.ts
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
  src/pages/Main/index.tsx
  src/router/Private.tsx
  src/router/Router.tsx
  src/router/lazy.ts
  src/store/user.ts
  src/types/assets.d.ts
  src/types/space.type.ts
  src/utils/KkiriProvider.tsx
  src/utils/cookie.ts
  src/utils/tokenStorage.ts
Labels: ⚛️프론트엔드, 🏭 개발

#140 📝fix : api 문서에 따른 end_point 수정완료
  src/apis/comment/deleteComment.ts
  src/apis/comment/getComment.ts
  src/apis/comment/postComment.ts
  src/apis/post/deletePost.ts
  src/apis/post/getPostDetail.ts
  src/apis/post/patchPost.ts
  src/apis/post/postPost.ts
  src/apis/space/deleteSpace.ts
  src/apis/space/deleteSpaceTag.ts
  src/apis/space/deleteSpaceUser.ts
  src/apis/space/getSpaceCheckNickName.ts
  src/apis/space/getSpaceDetail.ts
  src/apis/space/getSpacePostList.ts
  src/apis/space/getSpaceTag.ts
  src/apis/space/patchSpace.ts
  src/apis/space/patchSpaceUser.ts
  src/apis/space/postSpaceTag.ts
  src/apis/user/getMyBookMarkList.ts
  src/apis/user/getMyCommentList.ts
  src/apis/user/getMyPostList.ts
  src/apis/user/patchUserInfo.ts
  src/apis/user/postLogout.ts
  src/components/Main/Comments/OneComment/OneComment.tsx
  src/components/Main/Comments/OneComment/style.ts
  src/components/Main/Comments/index.tsx
  src/components/Main/MainBody/MainBody.tsx
  src/components/Main/SearchBox/index.tsx
  src/components/Main/SearchBox/style.ts
  src/components/Main/SelectBox/components/Toggle.tsx
  src/components/Main/SelectBox/index.tsx
  src/components/Main/SelectBox/style.ts
  src/constants/api.ts
  src/hooks/api/comment/useCommentMutation.ts
  src/hooks/api/comment/useCommentQuery.ts
  src/hooks/api/space/useCheckUserNameQuery.ts
  src/hooks/api/space/useSpaceDeleteUserMutation.ts
  src/hooks/api/user/useLogOutMutation.ts
  src/layout/HeaderLayout/Header.tsx
  src/mocks/data/comment.mock.ts
  src/mocks/data/space.mock.ts
  src/mocks/handlers/post.ts
  src/mocks/handlers/space.ts
  src/mocks/handlers/user.ts
  src/modal/Detail/index.tsx
  src/pages/Main/index.tsx
  src/types/comment.type.ts
  src/types/main.type.ts
  src/types/space.type.ts
Labels: ⚙️설정, ⚛️프론트엔드, ✏️ 문서, 🏭 개발

#142 🌈feat : 스페이스 유저 api 진행 중
  src/App.tsx
  src/apis/post/patchPost.ts
  src/apis/post/postPost.ts
  src/apis/space/deleteSpace.ts
  src/apis/space/deleteSpaceTag.ts
  src/apis/space/deleteSpaceUser.ts
  src/apis/space/getSpaceDetail.ts
  src/apis/space/getSpaceList.ts
  src/apis/space/getSpacePostList.ts
  src/apis/space/getSpaceTag.ts
  src/apis/space/patchSpace.ts
  src/apis/space/patchSpaceUser.ts
  src/apis/space/postSpace.ts
  src/apis/space/postSpaceInvite.ts
  src/apis/space/postSpaceTag.ts
  src/assets/loading.gif
  src/assets/loading2.gif
  src/assets/png/DefaultProfile.png
  src/components/Create/MultipleImgBox/index.tsx
  src/components/Create/TagEditModal/index.tsx
  src/components/Main/Setting/index.tsx
  src/components/common/Calender/Calender.tsx
  src/components/common/Error/errorBoundary.tsx
  src/components/common/Error/index.tsx
  src/components/common/Error/style.ts
  src/components/common/InputBox/index.tsx
  src/components/common/InputBox/style.ts
  src/components/common/Loading/index.tsx
  src/components/common/UserListModal/UserList.tsx
  src/components/common/UserSettingModal/index.tsx
  src/hooks/api/post/usePostCreateMutation.ts
  src/hooks/api/post/usePostUpdateMutation.ts
  src/hooks/api/space/useSpaceCreateMutation.ts
  src/hooks/api/space/useSpaceInvitationMutation.ts
  src/hooks/api/space/useSpaceTagCreateMutation.ts
  src/hooks/api/space/useSpaceTagDeleteMutation.ts
  src/hooks/api/space/useSpaceUpdateMutation.ts
  src/hooks/api/space/useSpaceUserDeleteMutation.ts
  src/hooks/api/space/useSpaceUserInviteMutation.ts
  src/hooks/api/space/useSpaceUserUpdateMutation.ts
  src/hooks/api/space/useTagDeleteMutation.ts
  src/hooks/api/space/useTagMutation.ts
  src/hooks/api/user/useUserInfoMutation.ts
  src/layout/BackLayout/style.ts
  src/layout/HeaderLayout/Header.tsx
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/CreateSpace/style.ts
  src/pages/InviteCode/index.tsx
  src/pages/InviteCode/style.ts
  src/pages/Loading/index.tsx
  src/router/Private.tsx
  src/router/Router.tsx
  src/types/post.type.ts
  src/types/space.type.ts
Labels: ⚛️프론트엔드, 🏭 개발

#143 🌈feat : 메인페이지 api 연결완료
  .prettierrc
  src/apis/post/getPostDetail.ts
  src/components/Main/SearchBox/index.tsx
  src/components/Main/SelectBox/style.ts
  src/components/Main/Setting/index.tsx
  src/components/MyPage/MyCommentList.tsx
  src/components/MyPage/Skeleton/MyCommentList.skeleton.tsx
  src/components/common/Pagination/index.tsx
  src/components/common/UserSettingModal/index.tsx
  src/constants/auth.ts
  src/hooks/api/post/useBookMarkMutation.ts
  src/hooks/api/post/usePostDeleteMutation.ts
  src/hooks/api/post/usePostDetailQuery.ts
  src/hooks/api/space/useSpacePostListQuery.ts
  src/hooks/api/space/useSpaceUserUpdateMutation.ts
  src/layout/HeaderLayout/Header.tsx
  src/mocks/data/post.mock.ts
  src/mocks/data/space.mock.ts
  src/mocks/handlers/space.ts
  src/modal/Detail/index.tsx
  src/modal/Detail/style.ts
  src/pages/CreatePost/index.tsx
  src/pages/Main/index.tsx
  src/router/Private.tsx
  src/types/post.type.ts
  src/types/space.type.ts
Labels: ⚙️설정, ⚛️프론트엔드, 🖥️백엔드, 🏭 개발

#145 🌈feat : 디자인된 마커를 등록하였습니다.
  src/assets/svg/kakaomapMarker.svg
  src/components/Create/SearchMapModal/component/EventMarkerContainer.tsx
  src/components/Create/SearchMapModal/index.tsx
  src/components/Main/PostMap/components/EventMarkerContainer.tsx
  src/components/Main/PostMap/components/MarkerContents.tsx
  src/components/Main/PostMap/components/style.ts
  src/modal/Detail/index.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#144 🚀 feat: 메인 페이지 반응형 추가, 일부 리팩토링
  src/App.tsx
  src/apis/space/patchSpaceUser.ts
  src/assets/svg/selectlogo.svg
  src/assets/svg/signlogo.svg
  src/components/Auth/SocialKakao.tsx
  src/components/Auth/SocialNaver.tsx
  src/components/Create/SearchMapModal/index.tsx
  src/components/Create/SearchMapModal/style.ts
  src/components/Create/SelectIconModal/index.tsx
  src/components/Create/TagEditModal/index.tsx
  src/components/Create/TagEditModal/style.ts
  src/components/Main/MainBody/style.ts
  src/components/Main/MainHeader/style.ts
  src/components/Main/PostMap/components/style.ts
  src/components/Main/PostMap/style.ts
  src/components/MyPage/MyPostOrCommentList.tsx
  src/components/MyPage/style.ts
  src/components/common/BasicBox/style.ts
  src/components/common/BasicButton/style.ts
  src/components/common/Error/style.ts
  src/components/common/UserSettingModal/index.tsx
  src/constants/auth.ts
  src/layout/HeaderLayout/Header.tsx
  src/layout/HeaderLayout/style.ts
  src/pages/CreatePost/style.ts
  src/pages/CreateSpace/index.tsx
  src/pages/CreateSpace/style.ts
  src/pages/InviteCode/style.ts
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
  src/pages/Main/style.ts
  src/pages/MyPage/style.ts
  src/pages/SelectSpace/index.tsx
  src/pages/SelectSpace/style.ts
  src/styles/theme/theme.ts
  src/types/space.type.ts
Labels: ⚛️프론트엔드, 🏭 개발, 🎨 마크업 & 스타일링

#146 🌈 feat : 권한 없을 시 접근 제어, 반응형 수정
  src/components/Main/PostMap/components/style.ts
  src/components/Main/PostMap/style.ts
  src/components/MyPage/style.ts
  src/mocks/data/post.mock.ts
  src/modal/Detail/style.ts
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/Main/style.ts
  src/pages/SelectSpace/style.ts
  src/router/Private.tsx
  src/store/space.ts
  src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 🏭 개발, 🎨 디자인
