Repository space-401/FrontEnd, pull requests merged in 2023-09, with the labels that each got.

#32 [FE] CSS 토큰 적용, 공용 컴포넌트 일부 스토리 생성
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/BasicButton/BasicButton.stories.tsx
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/CircleIcon/CircleIcon.stories.tsx
  client/src/components/common/CircleIcon/CircleIcon.tsx
  client/src/components/common/CircleIcon/style.ts
  client/src/components/common/FlipCard/style.ts
  client/src/components/common/InputBox/InputBox.tsx
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/TextAreaBox.tsx
  client/src/components/common/TextAreaBox/style.ts
  client/src/components/layout/.gitkeep
  client/src/components/layout/FullScreenModal.tsx
  client/src/components/layout/FullScreenModal/FullScreenModal.tsx
  client/src/components/layout/FullScreenModal/style.ts
  client/src/components/layout/HeaderLayout/Header.tsx
  client/src/components/layout/HeaderLayout/HeaderLayout.tsx
  client/src/components/layout/HeaderLayout/style.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/InviteCode.tsx
  client/src/pages/InviteCode/style.ts
  client/src/styles/theme/styled-components.d.ts
  client/src/styles/theme/theme.ts
  client/src/styles/themes/colors.ts
  client/src/styles/themes/font_size.ts
  client/src/styles/themes/index.ts
  client/src/styles/themes/palette.ts
  client/src/styles/themes/theme.ts
  client/src/utils/CombinedProvider.tsx
  client/tsconfig.json
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#33 [FE] 플립카드 추가진행
  client/src/assets/svg/mapIcon.svg
  client/src/assets/svg/spaceDefault.svg
  client/src/components/FlipCard/FlipCard.stories.tsx
  client/src/components/FlipCard/FlipCard.tsx
  client/src/components/FlipCard/SpaceInfoBack/SpaceInfoBack.tsx
  client/src/components/FlipCard/SpaceInfoBack/style.ts
  client/src/components/FlipCard/SpaceSelectBack/SpaceSelectBack.tsx
  client/src/components/FlipCard/SpaceSelectBack/style.ts
  client/src/components/FlipCard/style.ts
  client/src/components/common/AvatarGroup/Avatars.tsx
  client/src/components/common/AvatarGroup/style.ts
  client/src/components/common/FlipCard/FlipCard.stories.tsx
  client/src/components/common/FlipCard/index.tsx
  client/src/components/common/FlipCard/style.ts
  client/src/components/common/SelectBox/SelectBox.stories.tsx
  client/src/components/common/SelectBox/SelectBox.tsx
  client/src/mocks/.gitkeep
  client/src/mocks/FlipCard/spaceInfo.mock.ts
  client/src/mocks/users.mock.ts
  client/src/styles/common.ts
  client/src/styles/theme/theme.ts
  client/src/types/assets.d.ts
  client/src/types/space.type.ts
  client/src/types/tag.type.ts
  client/src/types/user.type.ts
  client/src/utils/formatter.tsx
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#35 [FE] 캘린더 UI 진행중
  client/.storybook/preview.tsx
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/BasicDatePicker/index.tsx
  client/src/components/common/CircleIcon/CircleIcon.stories.tsx
  client/src/components/common/CircleIcon/CircleIcon.tsx
  client/src/components/common/CircleIcon/style.ts
  client/src/components/common/InputBox/InputBox.stories.tsx
  client/src/components/common/InputBox/InputBox.tsx
  client/src/components/common/InputBox/index.tsx
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/TextAreaBox.stories.tsx
  client/src/components/common/TextAreaBox/TextAreaBox.tsx
  client/src/components/common/TextAreaBox/index.tsx
  client/src/components/common/TextAreaBox/style.ts
  client/src/components/layout/FullScreenModal/FullScreenModal.tsx
  client/src/components/layout/HeaderLayout/Header.tsx
  client/src/components/layout/HeaderLayout/HeaderLayout.tsx
  client/src/components/layout/HeaderLayout/style.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/InviteCode.tsx
  client/src/pages/InviteCode/style.ts
  client/src/styles/global.ts
  client/src/styles/theme/theme.ts
  client/src/utils/KkiriProvider.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#34 [FE] 스타일 템플릿 추가 완료
  client/src/assets/svg/calenderIcon.svg
  client/src/assets/svg/mapIcon.svg
  client/src/assets/svg/markerIcon.svg
  client/src/assets/svg/moreIcon.svg
  client/src/assets/svg/personIcon.svg
  client/src/assets/svg/searchIcon.svg
  client/src/assets/svg/spaceDefault.svg
  client/src/assets/svg/tableIcon.svg
  client/src/assets/svg/userIcon.svg
  client/src/styles/theme/theme.ts
Labels: 🎨 디자인

#37 [FE] 캘린더 UI 추가
  client/index.css
  client/src/assets/svg/alarmIcon.svg
  client/src/components/common/BasicDatePicker/DatePicker.module.css
  client/src/components/common/BasicDatePicker/DatePicker.style.ts
  client/src/components/common/BasicDatePicker/day.ts
  client/src/components/common/BasicDatePicker/index.tsx
  client/src/components/layout/HeaderLayout/Header.tsx
  client/src/main.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/style.ts
  client/src/styles/reset.ts
  client/src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#38 [FE] 플립카드 수정
  client/src/components/FlipCard/FlipCard.tsx
  client/src/components/FlipCard/SpaceInfoBack/SpaceInfoBack.tsx
  client/src/components/FlipCard/SpaceInfoBack/style.ts
  client/src/components/FlipCard/SpaceSelectBack/SpaceSelectBack.tsx
  client/src/components/FlipCard/SpaceSelectBack/style.ts
  client/src/components/FlipCard/style.ts
Labels: ⚛️프론트엔드, 🔨 수정, 🐛 버그

#39 [FE] 폰트 추가
  client/src/pages/mainPage/components/MainHeader/style.ts
  client/src/styles/fonts/IBMPlexSansKR-Bold.woff
  client/src/styles/fonts/IBMPlexSansKR-ExtraLight.woff
  client/src/styles/fonts/IBMPlexSansKR-Light.woff
  client/src/styles/fonts/IBMPlexSansKR-Medium.woff
  client/src/styles/fonts/IBMPlexSansKR-Regular.woff
  client/src/styles/fonts/IBMPlexSansKR-SemiBold.woff
  client/src/styles/fonts/IBMPlexSansKR-Thin.woff
  client/src/styles/fonts/Pretendard-Black.ttf
  client/src/styles/fonts/Pretendard-Black.woff
  client/src/styles/fonts/Pretendard-Bold.ttf
  client/src/styles/fonts/Pretendard-Bold.woff
  client/src/styles/fonts/Pretendard-ExtraBold.ttf
  client/src/styles/fonts/Pretendard-ExtraBold.woff
  client/src/styles/fonts/Pretendard-ExtraLight.ttf
  client/src/styles/fonts/Pretendard-ExtraLight.woff
  client/src/styles/fonts/Pretendard-Light.ttf
  client/src/styles/fonts/Pretendard-Light.woff
  client/src/styles/fonts/Pretendard-Medium.ttf
  client/src/styles/fonts/Pretendard-Medium.woff
  client/src/styles/fonts/Pretendard-Regular.ttf
  client/src/styles/fonts/Pretendard-Regular.woff
  client/src/styles/fonts/Pretendard-SemiBold.ttf
  client/src/styles/fonts/Pretendard-SemiBold.woff
  client/src/styles/fonts/Pretendard-Thin.ttf
  client/src/styles/fonts/Pretendard-Thin.woff
  client/src/styles/global.ts
  client/src/styles/reset.ts
  client/src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#40 [FE] 캘린더 UI 다시 수정
  client/README.md
  client/index.css
  client/package-lock.json
  client/package.json
  client/src/assets/svg/calenderIcon.svg
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/BasicDatePicker/DatePicker.module.css
  client/src/components/common/BasicDatePicker/DatePicker.style.ts
  client/src/components/common/BasicDatePicker/day.ts
  client/src/components/common/BasicDatePicker/index.tsx
  client/src/components/common/BasicDatePicker/util.ts
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/style.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/styles/global.ts
  client/src/styles/reset.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#41 [FE] 사진 넣는 기능 진행중
  client/index.css
  client/package.json
  client/src/assets/svg/deleteIcon.svg
  client/src/assets/svg/leftArrow.svg
  client/src/assets/svg/photoIcon.svg
  client/src/assets/svg/rightArrow.svg
  client/src/components/FlipCard/style.ts
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/BasicDatePicker/index.tsx
  client/src/components/common/BasicDatePicker/util.ts
  client/src/components/common/CircleIcon/style.ts
  client/src/components/common/InputBox/index.tsx
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/style.ts
  client/src/components/layout/FullScreenModal/FullScreenModal.tsx
  client/src/components/layout/FullScreenModal/style.ts
  client/src/hooks/common/.gitkeep
  client/src/hooks/common/useSelectPhoto.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/InviteCode.tsx
  client/src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 🏭 개발, 🎨 마크업 & 스타일링

#42 [FE] selectInput 추가 진행중
  client/package-lock.json
  client/package.json
  client/src/assets/svg/chevron/chevron_down.svg
  client/src/assets/svg/chevron/chevron_left.svg
  client/src/assets/svg/chevron/chevron_right.svg
  client/src/assets/svg/chevron/chevron_up.svg
  client/src/components/common/AvatarGroup/Avatars.tsx
  client/src/components/common/SelectBox/SelectBox.stories.tsx
  client/src/components/common/SelectBox/SelectBox.tsx
  client/src/components/common/SelectBox/components/MenuList.tsx
  client/src/components/common/SelectBox/components/Toggle.tsx
  client/src/components/common/SelectBox/components/component/TagList.tsx
  client/src/components/common/SelectBox/components/component/UserList.tsx
  client/src/components/common/SelectBox/components/style.ts
  client/src/components/common/SelectBox/style.ts
  client/src/hooks/common/use-dimensions.ts
  client/src/mocks/data/user/users.mock.ts
  client/src/pages/mainPage/MainPage.stories.tsx
  client/src/pages/mainPage/components/MainBody/MainBody.tsx
  client/src/pages/mainPage/components/MainBody/style.ts
  client/src/pages/mainPage/components/MainHeader/MainHeader.tsx
  client/src/pages/mainPage/components/MainHeader/style.ts
  client/src/styles/global.ts
  client/src/styles/reset.ts
  client/src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 💡 제안, 🎨 디자인, 🎨 마크업 & 스타일링

#43 [FE] 메인페이지 헤더 레이아웃 적용
  client/package-lock.json
  client/package.json
  client/src/components/common/Calender/Calender.css
  client/src/components/common/Calender/index.tsx
  client/src/components/common/Calender/util.ts
  client/src/components/layout/FullScreenModal/style.ts
  client/src/components/layout/HeaderLayout/HeaderLayout.tsx
  client/src/components/layout/HeaderLayout/style.ts
  client/src/main.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/InviteCode/style.ts
  client/src/pages/PhotoEditPage/index.tsx
  client/src/pages/PhotoEditPage/style.ts
  client/src/pages/mainPage/MainPage.stories.tsx
  client/src/pages/mainPage/components/MainBody/MainBody.tsx
  client/src/pages/mainPage/components/MainBody/style.ts
  client/src/pages/mainPage/components/MainHeader/MainHeader.tsx
  client/src/pages/mainPage/components/MainHeader/style.ts
  client/src/pages/mainPage/index.tsx
  client/src/pages/mainPage/style.ts
  client/src/router/Router.tsx
  client/src/styles/global.ts
  client/src/styles/reset.ts
  client/src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#44 [FE] 메인페이지 SelectBox 추가
  client/src/components/FlipCard/FlipCard.tsx
  client/src/components/common/SelectBox/SelectBox.stories.tsx
  client/src/components/common/SelectBox/SelectBox.tsx
  client/src/components/common/SelectBox/components/MenuList.tsx
  client/src/components/common/SelectBox/components/component/TagList.tsx
  client/src/components/common/SelectBox/components/component/UserList.tsx
  client/src/components/common/SelectBox/components/style.ts
  client/src/components/common/SelectBox/style.ts
  client/src/mocks/data/FlipCard/spaceInfo.mock.ts
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/mainPage/MainPage.stories.tsx
  client/src/pages/mainPage/components/MainBody/MainBody.tsx
  client/src/pages/mainPage/components/MainBody/style.ts
  client/src/pages/mainPage/components/MainHeader/MainHeader.tsx
  client/src/pages/mainPage/components/MainHeader/style.ts
  client/src/pages/mainPage/index.tsx
  client/src/pages/mainPage/style.ts
  client/src/styles/theme/theme.ts
  client/src/types/main.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#45 [FE] 헤더 레이아웃 수정
  client/src/components/layout/FullScreenModal/style.ts
  client/src/components/layout/HeaderLayout/HeaderLayout.tsx
  client/src/components/layout/HeaderLayout/style.ts
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/style.ts
  client/src/pages/mainPage/index.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#46 [FE] 코드 포맷팅 누락
  client/src/components/common/SelectBox/SelectBox.stories.tsx
  client/src/components/common/SelectBox/SelectBox.tsx
  client/src/components/common/SelectBox/components/MenuList.tsx
  client/src/components/common/SelectBox/components/component/UserList.tsx
  client/src/components/common/SelectBox/components/style.ts
  client/src/components/common/SelectBox/style.ts
  client/src/hooks/common/use-dimensions.ts
  client/src/mocks/data/FlipCard/spaceInfo.mock.ts
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/mainPage/MainPage.stories.tsx
  client/src/pages/mainPage/components/MainBody/MainBody.tsx
  client/src/pages/mainPage/components/MainBody/style.ts
  client/src/pages/mainPage/components/MainHeader/MainHeader.tsx
  client/src/pages/mainPage/components/MainHeader/style.ts
  client/src/pages/mainPage/style.ts
  client/src/types/main.type.ts
Labels: ⚛️프론트엔드, 🔨 수정, 🏭 개발

#47 [FE]dselect box 개발 진행
  client/src/assets/svg/trash.svg
  client/src/pages/CreatePost/components/SelectBox/SelectBox.stories.tsx
  client/src/pages/CreatePost/components/SelectBox/SelectBox.tsx
  client/src/pages/CreatePost/components/SelectBox/components/MenuList.tsx
  client/src/pages/CreatePost/components/SelectBox/components/Toggle.tsx
  client/src/pages/CreatePost/components/SelectBox/components/component/SelectList.tsx
  client/src/pages/CreatePost/components/SelectBox/components/component/TagList.tsx
  client/src/pages/CreatePost/components/SelectBox/components/component/UserList.tsx
  client/src/pages/CreatePost/components/SelectBox/components/style.ts
  client/src/pages/CreatePost/components/SelectBox/style.ts
  client/src/pages/mainPage/MainPage.stories.tsx
  client/src/pages/mainPage/components/MainBody/MainBody.tsx
  client/src/pages/mainPage/components/MainHeader/MainHeader.tsx
  client/src/pages/mainPage/components/SelectBox/SelectBox.tsx
  client/src/pages/mainPage/components/SelectBox/components/MenuList.tsx
  client/src/pages/mainPage/components/SelectBox/components/Toggle.tsx
  client/src/pages/mainPage/components/SelectBox/components/component/TagList.tsx
  client/src/pages/mainPage/components/SelectBox/components/component/UserList.tsx
  client/src/pages/mainPage/components/SelectBox/components/style.ts
  client/src/pages/mainPage/components/SelectBox/style.ts
  client/src/pages/mainPage/index.tsx
  client/src/types/main.type.ts
  client/src/types/user.type.ts
  client/src/utils/typeGuard.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#48 🌈feat : 사진 편집 기능 진행중
  client/package-lock.json
  client/package.json
  client/src/components/CreateSelectBox/SelectBox.stories.tsx
  client/src/components/CreateSelectBox/components/MenuList.tsx
  client/src/components/CreateSelectBox/components/Toggle.tsx
  client/src/components/CreateSelectBox/components/component/SelectList.tsx
  client/src/components/CreateSelectBox/components/component/TagList.tsx
  client/src/components/CreateSelectBox/components/component/UserList.tsx
  client/src/components/CreateSelectBox/components/style.ts
  client/src/components/CreateSelectBox/index.tsx
  client/src/components/CreateSelectBox/style.ts
  client/src/components/MainSelectBox/components/MenuList.tsx
  client/src/components/MainSelectBox/components/Toggle.tsx
  client/src/components/MainSelectBox/components/component/TagList.tsx
  client/src/components/MainSelectBox/components/component/UserList.tsx
  client/src/components/MainSelectBox/components/style.ts
  client/src/components/MainSelectBox/index.tsx
  client/src/components/MainSelectBox/style.ts
  client/src/components/common/ImageEditModal/Cropper.css
  client/src/components/common/ImageEditModal/PhotoCropper.tsx
  client/src/components/common/ImageEditModal/index.tsx
  client/src/components/common/ImageEditModal/style.ts
  client/src/layout/FullScreenModal/FullScreenModal.tsx
  client/src/layout/FullScreenModal/style.ts
  client/src/layout/HeaderLayout/Header.tsx
  client/src/layout/HeaderLayout/HeaderLayout.tsx
  client/src/layout/HeaderLayout/style.ts
  client/src/main.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/InviteCode/InviteCode.stories.tsx
  client/src/pages/InviteCode/index.tsx
  client/src/pages/PhotoEditPage/index.tsx
  client/src/pages/PhotoEditPage/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/MainBody/style.ts
  client/src/pages/main/MainHeader/MainHeader.tsx
  client/src/pages/main/MainHeader/style.ts
  client/src/pages/main/MainPage.stories.tsx
  client/src/pages/main/index.tsx
  client/src/pages/main/style.ts
  client/src/router/Router.tsx
  client/src/styles/common.ts
  client/src/styles/global.ts
  client/src/styles/theme/font.ts
Labels: ⚛️프론트엔드, 🏭 개발, 🎨 마크업 & 스타일링

#50 [FE] 메인페이지 수정 진행
  client/src/components/FlipCard/FlipCard.stories.tsx
  client/src/components/FlipCard/FlipCard.tsx
  client/src/components/FlipCard/style.ts
  client/src/components/MainSearchBox/index.tsx
  client/src/components/MainSearchBox/style.ts
  client/src/components/MainSelectBox/index.tsx
  client/src/components/MainSelectBox/style.ts
  client/src/layout/HeaderLayout/style.ts
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/MainBody/style.ts
  client/src/pages/main/MainPage.stories.tsx
  client/src/pages/main/index.tsx
  client/src/styles/theme/font.ts
  client/src/types/main.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#51 [FE] 카카오맵 추가하기 진행중
  client/.env.sample
  client/.storybook/preview-head.html
  client/.storybook/preview.tsx
  client/package-lock.json
  client/package.json
  client/src/components/MainSelectBox/style.ts
  client/src/components/kakaoMap/index.tsx
  client/src/components/kakaoMap/kakaomap.stories.tsx
  client/src/mocks/data/map/map.mock.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/types/map.type.ts
  client/src/utils/KkiriProvider.tsx
  client/tsconfig.json
  client/vite.config.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#53 Feat/image
  client/package-lock.json
  client/package.json
  client/src/components/CreateSelectBox/components/Toggle.tsx
  client/src/components/CreateSelectBox/components/style.ts
  client/src/components/CreateSelectBox/index.tsx
  client/src/components/CreateSelectBox/style.ts
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/Calender/Calender.css
  client/src/components/common/Calender/index.tsx
  client/src/components/common/ImageEditModal/Cropper.css
  client/src/components/common/ImageEditModal/Cropper.tsx
  client/src/components/common/ImageEditModal/ImageEditModal.tsx
  client/src/components/common/ImageEditModal/PhotoCropper.tsx
  client/src/components/common/ImageEditModal/index.tsx
  client/src/components/common/ImageEditModal/style.ts
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/style.ts
  client/src/hooks/common/useSelectPhoto.ts
  client/src/mocks/data/createPostPage/createPost.mock.ts
  client/src/pages/CreatePost/index.tsx
  client/src/router/Router.tsx
  client/src/types/crop.type.ts
Labels: ⚛️프론트엔드, 🏭 개발

#52 [FE] font 미적용 버그 수정
  client/src/styles/fonts/font.css
  client/src/styles/global.ts
  client/src/styles/theme/font.ts
Labels: 🔨 수정, 🐛 버그

#54 [FE] 메인페이지 지도 추가
  client/.storybook/preview-head.html
  client/.storybook/preview.tsx
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/MainSearchBox/index.tsx
  client/src/components/MainSelectBox/style.ts
  client/src/components/PostMap/MapComponent.tsx
  client/src/components/PostMap/components/EventMarkerContainer.tsx
  client/src/components/PostMap/components/LeftSection.tsx
  client/src/components/PostMap/components/style.ts
  client/src/components/PostMap/style.ts
  client/src/components/SearchMap/searchMap.tsx
  client/src/components/SearchMap/style.ts
  client/src/components/kakaoMap/index.tsx
  client/src/components/kakaoMap/kakaomap.stories.tsx
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/MainHeader/MainHeader.tsx
  client/src/pages/main/index.tsx
  client/src/types/main.type.ts
  client/src/types/map.type.ts
  client/src/utils/KkiriProvider.tsx
  client/tsconfig.json
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#55 [FE] 카카오맵 마커 등록 완료, 맵 페이지 카드 제작중
  client/.env.sample
  client/src/components/CreateSelectBox/components/component/SelectList.tsx
  client/src/components/CreateSelectBox/components/style.ts
  client/src/components/CreateSelectBox/style.ts
  client/src/components/MainSearchBox/style.ts
  client/src/components/MainSelectBox/components/style.ts
  client/src/components/MainSelectBox/style.ts
  client/src/components/PostMap/MapComponent.tsx
  client/src/components/PostMap/components/EventMarkerContainer.tsx
  client/src/components/PostMap/components/LeftSection.tsx
  client/src/components/PostMap/components/MarkerContents.stories.tsx
  client/src/components/PostMap/components/MarkerContents.tsx
  client/src/components/PostMap/components/One-PostMapCard.tsx
  client/src/components/PostMap/components/style.ts
  client/src/components/PostMap/style.ts
  client/src/components/common/AvatarGroup/Avatars.tsx
  client/src/components/common/Calender/index.tsx
  client/src/components/common/CircleIcon/style.ts
  client/src/components/common/ImageEditModal/style.ts
  client/src/components/common/InputBox/style.ts
  client/src/components/common/TextAreaBox/style.ts
  client/src/constants/.gitkeep
  client/src/constants/APPKEY.ts
  client/src/layout/FullScreenModal/style.ts
  client/src/layout/HeaderLayout/style.ts
  client/src/mocks/data/FlipCard/spaceInfo.mock.ts
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/mocks/data/map/map.mock.ts
  client/src/pages/main/MainBody/style.ts
  client/src/pages/main/MainHeader/MainHeader.tsx
  client/src/pages/main/MainHeader/style.ts
  client/src/pages/main/style.ts
  client/src/styles/theme/theme.ts
  client/src/types/map.type.ts
  client/src/types/space.type.ts
  client/src/utils/formatter.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#56 [FE] 다중이미지 선택 기능 추가
  client/src/assets/svg/photo/multipleIcon.svg
  client/src/assets/svg/photo/plusIcon.svg
  client/src/assets/svg/photo/sizeChangeIcon.svg
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/ImageEditModal/Cropper.css
  client/src/components/common/ImageEditModal/Cropper.tsx
  client/src/components/common/ImageEditModal/ImageEditModal.tsx
  client/src/components/common/ImageEditModal/MultipleView.tsx
  client/src/components/common/ImageEditModal/style.ts
  client/src/hooks/common/useSelectPhoto.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#57 [FE] theme 수정
  client/src/components/PostMap/components/style.ts
  client/src/components/PostMap/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/MainHeader/style.ts
Labels: 🔨 수정, 🎨 디자인

#59 [FE] 상세페이지 작업 진행
  client/package-lock.json
  client/package.json
  client/src/components/FlipCard/FlipCard.tsx
  client/src/components/FlipCard/SpaceInfoBack/style.ts
  client/src/components/FlipCard/style.ts
  client/src/components/PostMap/components/LeftSection.tsx
  client/src/components/PostMap/components/One-PostMapCard.tsx
  client/src/components/PostMap/components/style.ts
  client/src/components/PostMap/index.tsx
  client/src/constants/APPKEY.ts
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/index.tsx
  client/src/store/modal.ts
  client/src/types/main.type.ts
  client/tsconfig.path.json
Labels: ⚛️프론트엔드, 🐛 버그, 🎨 마크업 & 스타일링

#60 [FE] 사진 좌표 기록 진행중
  client/src/components/common/ImageEditModal/Cropper.tsx
  client/src/components/common/ImageEditModal/ImageEditModal.tsx
  client/src/components/common/ImageEditModal/MultipleView.tsx
  client/src/hooks/common/use-location.ts
  client/src/layout/HeaderLayout/style.ts
  client/src/pages/CreatePost/index.tsx
  client/src/store/modal.ts
Labels: ⚛️프론트엔드, 🏭 개발

#61 [FE] 디테일 페이지 추가진행, Confirm Modal 제작완료
  client/src/assets/svg/menu.svg
  client/src/components/FlipCard/SpaceInfoBack/SpaceInfoBack.tsx
  client/src/components/PostMap/components/LeftSection.tsx
  client/src/components/PostMap/components/MarkerContents.stories.tsx
  client/src/components/PostMap/index.tsx
  client/src/components/common/ConfirmModal/ConfirmModal.tsx
  client/src/components/common/ConfirmModal/style.ts
  client/src/mocks/data/DetailPage/detailPage.mock.ts
  client/src/mocks/data/FlipCard/spaceInfo.mock.ts
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/index.tsx
  client/src/store/modal.ts
  client/src/types/space.type.ts
  client/src/utils/formatter.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#62 [FE] 이미지 편집 수정
  client/src/App.tsx
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/ImageEditModal/Cropper.tsx
  client/src/components/common/ImageEditModal/ImageEditModal.tsx
  client/src/components/common/ImageEditModal/MultipleView.tsx
  client/src/components/common/ImageEditModal/style.ts
  client/src/components/common/InputBox/index.tsx
  client/src/components/common/MultipleImgBox/index.tsx
  client/src/components/common/MultipleImgBox/style.ts
  client/src/components/common/TextAreaBox/index.tsx
  client/src/hooks/common/use-location.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/InviteCode/index.tsx
  client/src/utils/handleFiles.tsx
Labels: ⚛️프론트엔드, 🏭 개발, 🎨 마크업 & 스타일링

#63 [FE] 상세페이지 댓글 추가, Alert Modal 추가완료
  client/src/components/FlipCard/FlipCard.stories.tsx
  client/src/components/Main/Comments/OneComment/OneComment.tsx
  client/src/components/Main/Comments/OneComment/style.ts
  client/src/components/Main/Comments/index.tsx
  client/src/components/Main/Comments/style.ts
  client/src/components/Main/FlipCard/FlipCard.tsx
  client/src/components/Main/FlipCard/SpaceInfoBack/SpaceInfoBack.tsx
  client/src/components/Main/FlipCard/SpaceInfoBack/style.ts
  client/src/components/Main/FlipCard/SpaceSelectBack/SpaceSelectBack.tsx
  client/src/components/Main/FlipCard/SpaceSelectBack/style.ts
  client/src/components/Main/FlipCard/style.ts
  client/src/components/Main/PostMap/components/EventMarkerContainer.tsx
  client/src/components/Main/PostMap/components/LeftSection.tsx
  client/src/components/Main/PostMap/components/MarkerContents.stories.tsx
  client/src/components/Main/PostMap/components/MarkerContents.tsx
  client/src/components/Main/PostMap/components/One-PostMapCard.tsx
  client/src/components/Main/PostMap/components/style.ts
  client/src/components/Main/PostMap/index.tsx
  client/src/components/Main/PostMap/style.ts
  client/src/components/Main/SearchBox/index.tsx
  client/src/components/Main/SearchBox/style.ts
  client/src/components/Main/SelectBox/components/MenuList.tsx
  client/src/components/Main/SelectBox/components/Toggle.tsx
  client/src/components/Main/SelectBox/components/component/TagList.tsx
  client/src/components/Main/SelectBox/components/component/UserList.tsx
  client/src/components/Main/SelectBox/components/style.ts
  client/src/components/Main/SelectBox/index.tsx
  client/src/components/Main/SelectBox/style.ts
  client/src/components/common/AlertModal/AlertModal.tsx
  client/src/components/common/AlertModal/style.ts
  client/src/components/common/ConfirmModal/ConfirmModal.tsx
  client/src/mocks/data/DetailPage/comment.mock.ts
  client/src/mocks/data/DetailPage/detailPage.mock.ts
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/store/user.ts
  client/src/styles/theme/theme.ts
  client/src/types/space.type.ts
  client/src/utils/time-helper.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#65 [FE] swiper로 이미지 캐루셀 추가
  client/.env.sample
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/assets/svg/leftArrow.svg
  client/src/assets/svg/rightArrow.svg
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/Calender/Calender.css
  client/src/components/common/ImageEditModal/ImageEditModal.tsx
  client/src/components/common/ImageEditModal/style.ts
  client/src/components/common/ImgSlider/index.tsx
  client/src/components/common/ImgSlider/style.css
  client/src/components/common/InputBox/style.ts
  client/src/components/common/MultipleImgBox/style.ts
  client/src/components/common/TextAreaBox/style.ts
  client/src/pages/CreatePost/index.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#66 [FE] alertModal 추가, state수정
  client/.env.sample
  client/package-lock.json
  client/package.json
  client/src/components/Main/Comments/index.tsx
  client/src/components/Main/SearchBox/index.tsx
  client/src/components/Main/SelectBox/index.tsx
  client/src/components/common/AlertModal/AlertModal.tsx
  client/src/components/common/AlertModal/style.ts
  client/src/layout/HeaderLayout/HeaderLayout.tsx
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/index.tsx
  client/src/router/Router.tsx
  client/src/store/modal.ts
  client/src/types/modal.type.ts
Labels: ⚛️프론트엔드, 🤖 기능, 🎨 마크업 & 스타일링

#67 [FE] 상세페이지 제작완료, uuid 라이브러리 추가
  client/package-lock.json
  client/package.json
  client/src/assets/svg/bookmark/empty.svg
  client/src/assets/svg/bookmark/fill.svg
  client/src/components/Detail/OneMention.tsx
  client/src/components/Detail/style.ts
  client/src/components/Main/Comments/OneComment/OneComment.tsx
  client/src/components/Main/Comments/OneComment/style.ts
  client/src/components/Main/Comments/index.tsx
  client/src/components/Main/Comments/style.ts
  client/src/components/Main/SearchBox/index.tsx
  client/src/components/Main/SelectBox/index.tsx
  client/src/components/common/AlertModal/AlertModal.tsx
  client/src/components/common/AlertModal/style.ts
  client/src/layout/HeaderLayout/HeaderLayout.tsx
  client/src/mocks/data/DetailPage/comment.mock.ts
  client/src/mocks/data/DetailPage/detailPage.mock.ts
  client/src/mocks/data/user/users.mock.ts
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/index.tsx
  client/src/store/modal.ts
  client/src/types/modal.type.ts
  client/src/types/space.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#68 [FE] 상세페이지 개발 진행중, 헤더 추가변경
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/style.ts
  client/src/layout/HeaderLayout/Header.tsx
  client/src/layout/HeaderLayout/style.ts
  client/src/mocks/data/Header/header.mock.ts
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/main/MainHeader/MainHeader.tsx
  client/src/pages/main/MainHeader/style.ts
  client/src/pages/main/index.tsx
  client/src/store/modal.ts
  client/src/types/main.type.ts
  client/src/types/user.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#72 [FE] 메인 페이지 사이드 모달 추가
  client/src/assets/svg/crown.svg
  client/src/assets/svg/defaultProfileImg.svg
  client/src/assets/svg/mainSetting/crown.svg
  client/src/assets/svg/mainSetting/logout.svg
  client/src/assets/svg/mainSetting/user.svg
  client/src/assets/svg/whiteDeleteIcon.svg
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/ProfileAndUserNameChangeModal.tsx
  client/src/components/Main/Setting/components/UserList.tsx
  client/src/components/Main/Setting/components/style.ts
  client/src/components/Main/Setting/style.ts
  client/src/components/common/ConfirmModal/ConfirmModal.tsx
  client/src/layout/HeaderLayout/HeaderLayout.tsx
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/MainHeader/MainHeader.tsx
  client/src/pages/main/MainHeader/style.ts
  client/src/pages/main/index.tsx
  client/src/store/modal.ts
  client/src/types/main.type.ts
  client/src/types/user.type.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#73 [FE] 포스트, 이미지 생성 기능
  client/package-lock.json
  client/package.json
  client/src/assets/cat.jpg
  client/src/assets/svg/photo/deleteIcon.svg
  client/src/components/common/BasicBox/index.tsx
  client/src/components/common/BasicBox/style.ts
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/Calender/Calender.css
  client/src/components/common/Calender/index.tsx
  client/src/components/common/ConfirmModal/ConfirmModal.tsx
  client/src/components/common/ImageEditModal/ImageEditModal.tsx
  client/src/components/common/ImageEditModal/ImagesEditModal.tsx
  client/src/components/common/ImageEditModal/ImgCounter.tsx
  client/src/components/common/ImageEditModal/style.ts
  client/src/components/common/ImgSlider/index.tsx
  client/src/components/common/MultipleImgBox/index.tsx
  client/src/components/common/MultipleImgBox/style.ts
  client/src/main.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreateSpace/index.tsx
  client/src/types/crop.type.ts
  client/src/types/image.type.ts
  client/src/utils/fileConvertor.tsx
  client/src/utils/handleFiles.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#74 [FE] alert 모달 추가, 사이드 모달 변경, 페이지네이션 추가
  client/src/components/CreateSelectBox/SelectBox.stories.tsx
  client/src/components/Main/PostMap/components/LeftSection.tsx
  client/src/components/Main/PostMap/index.tsx
  client/src/components/Main/SelectBox/style.ts
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/UserList.tsx
  client/src/components/Main/Setting/components/style.ts
  client/src/components/Main/Setting/style.ts
  client/src/components/common/AlertModal/AlertModal.tsx
  client/src/components/common/Pagination/index.tsx
  client/src/components/common/Pagination/style.ts
  client/src/layout/HeaderLayout/HeaderLayout.tsx
  client/src/mocks/data/MainPage/mainPage.mock.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/store/modal.ts
  client/src/types/main.type.ts
  client/src/types/modal.type.ts
Labels: ⚛️프론트엔드, 🎨 디자인, 🎨 마크업 & 스타일링

#82 [FE] FlipCard 수정, selectBox 버그수정
  client/src/components/Main/FlipCard/SpaceInfoBack/SpaceInfoBack.tsx
  client/src/components/Main/FlipCard/SpaceSelectBack/SpaceSelectBack.tsx
  client/src/components/Main/FlipCard/SpaceSelectBack/style.ts
  client/src/components/Main/SelectBox/style.ts
  client/src/components/common/FlipCard/FlipCard.tsx
  client/src/components/common/FlipCard/SpaceInfoBack/SpaceInfoBack.tsx
  client/src/components/common/FlipCard/SpaceInfoBack/style.ts
  client/src/components/common/FlipCard/style.ts
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/styles/theme/theme.ts
Labels: ⚛️프론트엔드, 🐛 버그, 🎨 디자인

#83 [FE] 마이페이지 추가 진행중
  client/src/assets/svg/api/google.svg
  client/src/assets/svg/api/kakao.svg
  client/src/assets/svg/api/naver.svg
  client/src/assets/svg/page.svg
  client/src/layout/HeaderLayout/style.ts
  client/src/mocks/data/Account/AccountMock.ts
  client/src/pages/MyPage/MyBody/components/AccountManagement.tsx
  client/src/pages/MyPage/MyBody/components/BookMarkList.tsx
  client/src/pages/MyPage/MyBody/components/MyPostOrCommentList.tsx
  client/src/pages/MyPage/MyBody/components/style.ts
  client/src/pages/MyPage/MyBody/index.tsx
  client/src/pages/MyPage/MyBody/style.ts
  client/src/pages/MyPage/Navbar/index.tsx
  client/src/pages/MyPage/Navbar/style.ts
  client/src/pages/MyPage/index.tsx
  client/src/pages/MyPage/style.ts
  client/src/router/Router.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#84 [FE] 캘린더 css 수정
  client/package.json
  client/src/assets/svg/leftArrow.svg
  client/src/assets/svg/rightArrow.svg
  client/src/components/Create/CreateSelectBox/index.tsx
  client/src/components/Create/ImageEditModal/Cropper.tsx
  client/src/components/Create/ImageEditModal/ImageEditModal.tsx
  client/src/components/Create/ImageEditModal/ImagesEditModal.tsx
  client/src/components/Create/ImageEditModal/ImgCounter.tsx
  client/src/components/Create/ImgSlider/index.tsx
  client/src/components/Create/MultipleImgBox/index.tsx
  client/src/components/Create/SearchMapModal/index.tsx
  client/src/components/Create/SelectIconModal/index.tsx
  client/src/components/Main/Comments/OneComment/OneComment.tsx
  client/src/components/common/BasicButton/index.tsx
  client/src/components/common/BasicButton/style.ts
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/Calender/calender.css
  client/src/components/common/Calender/style.ts
  client/src/components/common/Calender/util.ts
  client/src/hooks/common/useValidate.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/Detail/index.tsx
  client/src/pages/InviteCode/index.tsx
  client/src/pages/main/MainBody/MainBody.tsx
  client/src/pages/main/MainHeader/MainHeader.tsx
  client/src/pages/main/index.tsx
  client/src/styles/theme/theme.ts
  client/src/types/image.type.ts
  client/src/types/modal.type.ts
  client/src/types/post.type.ts
  client/src/utils/time-helper.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#88 [FE] 폴더명 변경
  client/package-lock.json
  client/src/pages/Main/MainBody/MainBody.tsx
  client/src/pages/Main/MainBody/style.ts
  client/src/pages/Main/MainHeader/MainHeader.tsx
  client/src/pages/Main/MainHeader/style.ts
  client/src/pages/Main/MainPage.stories.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/style.ts
Labels: ⚛️프론트엔드

#89 [FE] create 페이지 반응형 작업
  client/src/components/Create/ImageEditModal/Cropper.tsx
  client/src/components/Create/ImageEditModal/ImageEditModal.tsx
  client/src/components/Create/ImageEditModal/ImagesEditModal.tsx
  client/src/components/Create/ImageEditModal/style.ts
  client/src/components/Create/ImgSlider/index.tsx
  client/src/components/common/Calender/Calender.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/Main/MainBody/MainBody.tsx
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#91 [FE] 프로필 이미지 편집 모달 생성
  client/src/assets/svg/closedEye.svg
  client/src/assets/svg/showEye.svg
  client/src/components/Create/CreateSelectBox/index.tsx
  client/src/components/Create/ImageEditModal/CircleCropper.css
  client/src/components/Create/ImageEditModal/CircleCropper.tsx
  client/src/components/Create/ImageEditModal/ImageEditModal.tsx
  client/src/components/Create/ImageEditModal/ImagesEditModal.tsx
  client/src/components/Create/ImageEditModal/style.ts
  client/src/components/Create/MultipleImgBox/index.tsx
  client/src/components/Main/Setting/components/ProfileAndUserNameChangeModal.tsx
  client/src/components/Main/Setting/components/style.ts
  client/src/components/common/Calender/Calender.tsx
  client/src/components/common/CircleIcon/CircleIcon.tsx
  client/src/components/common/CircleIcon/style.ts
  client/src/components/common/InputBox/index.tsx
  client/src/modal/Alert/AlertModal.tsx
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/CreateSpace/index.tsx
  client/src/pages/CreateSpace/style.ts
  client/src/pages/InviteCode/index.tsx
  client/src/pages/InviteCode/style.ts
  client/src/router/Router.tsx
  client/src/store/modal.ts
Labels: ⚛️프론트엔드, 🎨 마크업 & 스타일링

#92 [FE] msw 연결적용
  client/mockServiceWorker.js
  client/package.json
  client/src/App.tsx
  client/src/apis/interceptors.ts
  client/src/apis/post/getPostList.ts
  client/src/apis/user/getRefreshToken.ts
  client/src/constants/api.ts
  client/src/constants/queryKey.ts
  client/src/hooks/api/post/usePostListQuery.ts
  client/src/mocks/api/.gitkeep
  client/src/mocks/browser.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/post.ts
  client/src/pages/Main/MainBody/MainBody.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/types/index.d.ts
  client/src/types/main.type.ts
  client/src/utils/KkiriProvider.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#94 [FE] 스페이스 선택 페이지, 렌딩 페이지 제작
  client/.storybook/preview.tsx
  client/src/assets/svg/login/google.svg
  client/src/assets/svg/login/kakao.svg
  client/src/assets/svg/login/naver.svg
  client/src/assets/svg/plusIcon.svg
  client/src/components/Create/ImageEditModal/CircleCropper.module.css
  client/src/components/Create/ImageEditModal/CircleCropper.tsx
  client/src/components/Create/ImageEditModal/style.ts
  client/src/components/Create/MultipleImgBox/index.tsx
  client/src/components/Create/MultipleImgBox/style.ts
  client/src/components/Main/Setting/SettingComponent.tsx
  client/src/components/Main/Setting/components/ProfileAndUserNameChangeModal.tsx
  client/src/components/Main/Setting/components/style.ts
  client/src/components/common/FlipCard/Back/PostInfoBack.tsx
  client/src/components/common/FlipCard/Back/SpaceInfoBack.tsx
  client/src/components/common/FlipCard/Back/style.ts
  client/src/components/common/FlipCard/FlipCard.tsx
  client/src/components/common/FlipCard/style.ts
  client/src/constants/path.ts
  client/src/mocks/data/SpaceList/spaceList.mock.ts
  client/src/pages/CreatePost/index.tsx
  client/src/pages/CreatePost/style.ts
  client/src/pages/Landing/index.tsx
  client/src/pages/Landing/style.ts
  client/src/pages/Main/PostList/style.ts
  client/src/pages/SelectSpace/index.tsx
  client/src/pages/SelectSpace/style.ts
  client/src/router/Router.tsx
  client/src/styles/theme/theme.ts
  client/src/types/post.type.ts
  client/src/types/space.type.ts
Labels: ⚛️프론트엔드, 🏭 개발, 🎨 마크업 & 스타일링
