Repository space-401/FrontEnd, pull requests merged in 2023-11, with the labels that each got.

#147 🌈feat: 로그인 코드 일부 수정
  package-lock.json
  src/App.tsx
  src/apis/AxiosInstance.ts
  src/apis/interceptors.ts
  src/components/Auth/SocialGoogle.tsx
  src/components/Auth/SocialKakao.tsx
  src/components/Auth/SocialNaver.tsx
  src/constants/auth.ts
  src/pages/Auth/index.tsx
  src/router/Private.tsx
  src/store/user.ts
  src/types/user.type.ts
Labels: ⚛️프론트엔드

#148 🌈feat : 댓글 api에 spaceId를 추가합니다.
  src/apis/comment/getComment.ts
  src/components/Main/Comments/index.tsx
  src/hooks/api/comment/useCommentQuery.ts
  src/modal/Detail/index.tsx
Labels: ⚛️프론트엔드, 🔨 수정, 🏭 개발

#149 🚧refactor : postComment 키값 변경
  src/apis/comment/postComment.ts
Labels: ⚛️프론트엔드, 🔨 수정, 🏭 개발

#150 ⚒️fix : 일부 타입 수정
  src/apis/AxiosInstance.ts
  src/apis/user/getLogin.ts
  src/apis/user/postLogin.ts
  src/apis/user/postLogout.ts
  src/components/common/UserSettingModal/index.tsx
  src/constants/api.ts
  src/hooks/api/space/useSpaceInfoQuery.ts
  src/hooks/api/user/useLogInMutation.ts
  src/hooks/api/user/useLogOutMutation.ts
  src/pages/Auth/index.tsx
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/InviteCode/index.tsx
  src/pages/SelectSpace/index.tsx
  src/store/user.ts
  src/types/post.type.ts
  src/types/space.type.ts
  src/utils/tokenStorage.ts
Labels: ⚛️프론트엔드

#153 🚧refactor: 리뷰 코드로 전체적인 수정 후 인터셉터, 리프레시 토큰 발급받는 부분 수정
  src/App.tsx
  src/apis/AxiosInstance.ts
  src/apis/interceptors.ts
  src/apis/post/getPostDetail.ts
  src/apis/post/patchPost.ts
  src/apis/post/postPost.ts
  src/apis/space/getSpaceDetail.ts
  src/apis/space/getSpaceList.ts
  src/apis/space/patchSpace.ts
  src/apis/space/patchSpaceUser.ts
  src/apis/space/postSpace.ts
  src/apis/user/getLogin.ts
  src/apis/user/getRefreshToken.ts
  src/apis/ws/.gitkeep
  src/components/Auth/SocialGoogle.tsx
  src/components/Create/SelectIconModal/index.tsx
  src/components/common/Error/errorBoundary.tsx
  src/components/common/UserSettingModal/index.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/post/usePostCreateMutation.ts
  src/hooks/api/post/usePostUpdateMutation.ts
  src/hooks/api/space/useSpaceCreateMutation.ts
  src/hooks/api/space/useSpaceUpdateMutation.ts
  src/pages/Auth/index.tsx
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
  src/pages/Main/index.tsx
  src/pages/SelectSpace/index.tsx
  src/router/Private.tsx
  src/store/user.ts
  src/utils/cookie.ts
  src/utils/tokenStorage.ts
Labels: ⚛️프론트엔드, 🏭 개발

#154 📝fix : 로그인 작업 완료
  src/apis/user/getLogin.ts
  src/apis/user/postLogout.ts
  src/components/Create/SelectIconModal/index.tsx
  src/components/MyPage/AccountManagement.tsx
  src/hooks/api/user/useLogOutMutation.ts
  src/hooks/api/user/useLoginQuery.ts
  src/mocks/data/comment.mock.ts
  src/mocks/data/post.mock.ts
  src/mocks/data/space.mock.ts
  src/mocks/data/user.mock.ts
  src/mocks/handlers/user.ts
  src/pages/Auth/index.tsx
  src/router/Private.tsx
  src/router/Router.tsx
  src/store/user.ts
  src/types/comment.type.ts
Labels: ⚛️프론트엔드, 🏭 개발, 🐛 버그

#155 🌈feat : comment 생성, 삭제시 다시 불러오기를 적용한다.
  src/apis/user/getLogin.ts
  src/components/Main/Comments/OneComment/OneComment.tsx
  src/components/Main/Comments/index.tsx
  src/hooks/api/comment/useCommentDeleteMutation.ts
  src/hooks/api/comment/useCommentMutation.ts
  src/hooks/api/user/useRefreshTokenQuery.ts
  src/modal/Detail/index.tsx
  src/types/comment.type.ts
Labels: ⚛️프론트엔드, 🏭 개발

#156 📝 fix : 포스트 스페이스 생성 및 수정, 리프레시 토큰 수정
  src/apis/interceptors.ts
  src/apis/post/getPostDetail.ts
  src/apis/post/patchPost.ts
  src/apis/post/postPost.ts
  src/apis/space/getSpaceDetail.ts
  src/apis/space/patchSpace.ts
  src/apis/space/patchSpaceUser.ts
  src/apis/space/postSpace.ts
  src/apis/user/getLogin.ts
  src/apis/user/getNewAccessToken.ts
  src/apis/user/getRefreshToken.ts
  src/components/Auth/SocialGoogle.tsx
  src/components/common/UserSettingModal/index.tsx
  src/constants/api.ts
  src/constants/auth.ts
  src/hooks/api/post/usePostCreateMutation.ts
  src/hooks/api/post/usePostUpdateMutation.ts
  src/hooks/api/user/useLoginQuery.ts
  src/mocks/data/user.mock.ts
  src/pages/Auth/index.tsx
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
Labels: ⚛️프론트엔드, 🏭 개발

#162 🚧refactor : console.log 삭제
  src/apis/space/getSpaceList.ts
  src/apis/space/patchSpaceUser.ts
  src/apis/user/getNewAccessToken.ts
  src/components/Create/CreateSelectBox/components/MenuList.tsx
  src/components/Create/ImageEditModal/CircleImageEditmodal.tsx
  src/components/Main/Setting/index.tsx
  src/components/common/Error/errorBoundary.tsx
  src/components/common/UserSettingModal/index.tsx
  src/hooks/common/useCompressImage.ts
  src/hooks/common/useResetError.ts
  src/pages/CreatePost/index.tsx
  src/pages/CreateSpace/index.tsx
  src/pages/Main/index.tsx
  src/router/Router.tsx
Labels: ⚛️프론트엔드, 🔨 수정
